language: node_js
sudo: false
env:
  - CXX=g++-4.8
node_js:
  - "node"
before_script:
  - npm install -g gulp
script: gulp test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
  - node_modules # NPM packages
