language: node_js
sudo: false
env:
  - CXX=g++-4.8
  - secure: B1LQmi3YK99bcaQ3s/uhH3ItWHq6lzpJ72tycXd/zciALc5lf0mgEm8A86f+bgiTkz8ylunhPXyI/+Qx6K47d++wkv6GmsaI873ZNb6mqdb7T9odCZV8HQHGm/1LbO+lRh+jZqHOVc1gk0VozJdLESgpJWJS/heVkpUvSYvGPe4U5H449XQoMZ/yxevdLGKRFc8KILn0WNKMie+DHGjQGFHNw82RIhF5b49+0wch/njtYM/IaHf9MpKY9mzbMHD+ZVOeo5wVwRrM4XcGONr0B9Du00F/Z20XdiMckphT67fZ6OYguKK/nMbSmO73rsyCYOzwR6+fesQitOs/IJmnRUz+Rd36pf0ICgliuEzHzroUq+xuC/jHSlbUqdGOBG7AP+Fn8HI7pGlK3FYvfks5eDvFhQ4Pe670gzzoGPOAJaqce7/qhZWEF/BjM3sW64Nryk+lSrB6o4/eXy5VpLT3ZGXHHV38qUcRsrmfppulmp5vOV/yL99AD5aHASsBwrdd6R5titrWmZ2qPrr42ph/8LISQJG4ls5f8LSSr2OxgIn6x2VhdIxrSjyx5qb4Oko+301+h7bEzXQodFm1xUsBD2YaMPDxKhx/XDbLqCRHYLAMj/gaSgospOmWqbADyY9g3SQigCmsJb8Yo4FGRcvBwsjJ3XRRpwq/IZJfNEoTwuo=
node_js:
  - node
before_script:
  - npm install -g gulp
script: gulp test-travis
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
cache:
  directories:
    - node_modules
